In [1]:
!pip install word2number
from word2number import w2n
import pandas as pd
import numpy as np
from sklearn import linear_model

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=0480d1b0a246b9d7f9ef48b849ff2464731284784af4c68c916e283f52070a52
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [4]:
df = pd.read_csv('hiring.csv')
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [5]:
df.test_score.median()

8.0

In [6]:
df.test_score = df.test_score.fillna(df.test_score.median())
df['experience'] = df['experience'].fillna("zero")
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [7]:
new_df = df.drop('salary',axis='columns')
new_df

experience  test_score  interview_score
0           0         8.0                9
1           0         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6
5           3         7.0               10
6          10         8.0                7
7          11         7.0                8

In [8]:
salary = df.salary
salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [9]:
reg = linear_model.LinearRegression()
reg.fit(new_df,salary)

LinearRegression()

In [10]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [11]:
reg.intercept_

17737.263464337688

In [12]:
reg.predict([[2, 9, 6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [14]:
reg.predict([[12, 10, 10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])